version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  # Postgres is handled at the top level MegaServer repo

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - postgres
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env
    labels:
      virtual.host: "plausible.smartworkssoftware.com" # change to your domain name
      virtual.port: "8000"
      virtual.tls-email: "jake@smartworkssoftware.com" # change to your email

volumes:
  event-data:
    driver: local
